name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/lcambier/testdocker:latest 
    steps:
    - name: Run in container
      run: |
          cd / && mpicxx hello_mpi.cpp   -o hello_mpi      && mpirun --allow-run-as-root -n 2 ./hello_mpi
          cd / && upcxx  hello_upcxx.cpp -o hello_upcxx -g && upcxx-run -n 2 ./hello_upcxx
